name: frontend

on: 
  workflow_call:
    inputs:
      navn: 
        required: false
        type: string
        default: "AAP"
        
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{inputs.navn}}
    - run: echo ${{secrets.AAP_TEST_SECRET}}
