name: Deploy

on:
  workflow_call:
    inputs:
      cluster:
        required: true
        type: string
        description: https://docs.nais.io/clusters/gcp/
      vars:
        required: false
        type: string
        description: Template file of environments variables to be interpolated in the manifest.
        default: ""
      tag:
        required: false
        type: string
        default: ${{ github.sha }}
        description: Git tag used when published to GAR (nais/docker-build-push)
      manifest:
        required: false
        type: string
        default: .nais/app.yml
        description: NAIS Application resource manifest
      imageSuffix:
        required: false
        type: string
        default: ""
        description: Suffix to append to the image name

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{inputs.cluster}}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: nais/login@40b72a35a18ddf2ad74b632461139ab838cc2a2f # v0
        id: login
        with:
          team: aap
      - uses: nais/deploy/actions/deploy@9850be311389ca754d9a9f2280615419d738c891 # v3
        env:
          PRINT_PAYLOAD: true
          CLUSTER: ${{ inputs.cluster }}
          RESOURCE: ${{ inputs.manifest }}
          VARS: ${{ inputs.vars }}
          VAR: image=${{ steps.login.outputs.registry }}/${{ github.event.repository.name }}${{ inputs.imageSuffix }}:${{ inputs.tag }}
