name: Deploy

on:
  workflow_call:
    inputs:
      cluster:
        required: true
        type: string
        description: https://docs.nais.io/clusters/gcp/
      vars:
        required: false
        type: string
        description: Template file of environments variables to be interpolated in the manifest.
        default: ""
      tag:
        required: false
        type: string
        default: ${{ github.sha }}
        description: Git tag used when published to GAR (nais/docker-build-push)
      manifest:
        required: false
        type: string
        default: .nais/app.yml
        description: NAIS Application resource manifest
      imageSuffix:
        required: false
        type: string
        default: ""
        description: Suffix to append to the image name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/login@v0
        id: login
        with:
          team: aap
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
      - uses: nais/deploy/actions/deploy@v1
        env:
          PRINT_PAYLOAD: true
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ inputs.cluster }}
          RESOURCE: ${{ inputs.manifest }}
          VARS: ${{ inputs.vars }}
          VAR: image=${{ steps.login.outputs.registry }}/${{ github.event.repository.name }}${{ inputs.imageSuffix }}:${{ inputs.tag }}
