on: 
  workflow_call:
    inputs:
      cluster:
        required: true
        type: string
        description: e.g. dev-gcp
      manifest:
        required: false
        type: string
        default: .nais/app.yml
        description: NAIS Application resource (aka manifest)
      vars:
        required: false
        type: string
        default: .nais/dev.yml
        description: yml/json with environment variables

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: nais/login@v0
        id: login
        with:
          team: aap
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
      - uses: nais/deploy/actions/deploy@v1
        env:
          PRINT_PAYLOAD: true
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ inputs.cluster }}
          RESOURCE: ${{ inputs.manifest }}
          VARS: ${{ inputs.vars }}
          VAR: image=${{ steps.login.outputs.registry }}/${{ github.event.repository.name }}:${{ github.sha }}
