name: frontend
on: 
  workflow_call:
    inputs:
      navn: 
        required: true
        type: string
        default: "AAP"
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: echo "hello"
