name: frontend
on: 
  workflow_call:
    inputs:
      navn: 
        required: false
        type: string
        default: "AAP"
    secrets: 
      hemmelig:
        required: true
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{inputs.navn}}
